name: Rudderstack E2E Automation CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2:00 AM UTC

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      RUDDERSTACK_EMAIL: ${{ secrets.RUDDERSTACK_EMAIL }}
      RUDDERSTACK_PASSWORD: ${{ secrets.RUDDERSTACK_PASSWORD }}
      RUDDERSTACK_URL: ${{ secrets.RUDDERSTACK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run E2E Tests (Headless)
        run: npm test

      - name: Upload Cucumber HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: reports/cucumber-report.html

      - name: Upload Cucumber JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-junit-report
          path: reports/cucumber-report.xml
